- hosts: all
  gather_facts: false
  vars:
    nova_auth_url: ''
    nova_username: ''
    nova_password: ''
    nova_tenant_name: demo
    nova_image_name: "cirros-0.3.2-x86_64-uec"
    nova_instance_name: autobot
    nova_instance_state: 'present'
    nova_flavor_name: m1.nano

    nova_group:
      group_name: antarctica
      instance_name: deceptacon
      instance_count: 3
  tasks:
    - name: "Setting nova instance state to: {{ nova_instance_state }}"
      local_action: 
        module: nova_compute
        login_username: "{{ nova_username }}"
        login_password: "{{ nova_password }}"
        login_tenant_name: "{{ nova_tenant_name }}"
        image_name: "{{ nova_image_name }}"
        name: "{{ nova_group.instance_name }}-{{ nova_group.group_name}}-{{ item }}"
        flavor_include: "{{ nova_flavor_name }}"
        auth_url: "{{ nova_auth_url }}"
        state: "{{ nova_instance_state }}"
        meta:
          group: "{{ nova_group.group_name }}"
      with_sequence: start=0 end={{ nova_group.instance_count|default(0) }}
